### ISSUE TITLE
[PaddleSlim] mobilenet_v1_ssd剪裁率是0

### ISSUE THREAD

**Issue by ZiruiChen** [PaddlePaddle/models#3110]
![image](https://user-images.githubusercontent.com/50459712/63013504-b4108500-becf-11e9-8040-6f08ded81118.png)
如图 pruned size 和pruned flops 是0 没有剪裁效果

**Comment by ZiruiChen** [comment]
![image](https://user-images.githubusercontent.com/50459712/63013577-db675200-becf-11e9-8b4b-a8cc1f5cfe31.png)
附上config

**Comment by ZiruiChen** [comment]
![image](https://user-images.githubusercontent.com/50459712/63013636-00f45b80-bed0-11e9-81b6-d8a9ac639595.png)
pruned_params: '*._sep_weights' 的原因

**Comment by ZiruiChen** [comment]
@wanghaoshuang

**Comment by ZiruiChen** [comment]
@wzzju

**Comment by ZiruiChen** [comment]
https://github.com/PaddlePaddle/models/issues/2985#issue-475066410

**Comment by ZiruiChen** [comment]
![image](https://user-images.githubusercontent.com/50459712/63031640-a8d14f80-bef7-11e9-91b2-4bc1ed7c8839.png)
尝试改变pruned_params 可以剪裁第一步 之后报错
![image](https://user-images.githubusercontent.com/50459712/63031610-9525e900-bef7-11e9-83d9-26b9840d51df.png)
![image](https://user-images.githubusercontent.com/50459712/63031745-d918ee00-bef7-11e9-9e55-f55afc4721f6.png)

**Comment by wanghaoshuang** [comment]
在你的配置文件中，需要改下quatization_strategy的start_epoch, 让quatization_strategy在prune_strategy之后一个epoch执行。

而且从效果上看，剪裁之后，一定要先训练几个epoch再做量化训练。

非常抱歉，我们会根据您的反馈完善下文档。

**Comment by ZiruiChen** [comment]
> 在你的配置文件中，需要改下quatization_strategy的start_epoch, 让quatization_strategy在prune_strategy之后一个epoch执行。
> 
> 而且从效果上看，剪裁之后，一定要先训练几个epoch再做量化训练。
> 
> 非常抱歉，我们会根据您的反馈完善下文档。

好的 但是修改了epoch之后 剪裁效果还是0呢 希望完善剪裁策略后能通知下我

**Comment by wanghaoshuang** [comment]
```
# step1: Pruning at epoch-0
# step2: Fine-tune at epoch-0
# step3: Quantization training from epoch-1 to epoch-2
version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            '*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    uniform_pruning_strategy:
        class: 'UniformPruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        target_ratio: 0.5
        pruned_params: '.*_sep_weights'
        metric_name: 'acc_top1'
    quantization_strategy:
        class: 'QuantizationStrategy'
        start_epoch: 1
        end_epoch: 2
        float_model_save_path: './output/float'
        mobile_model_save_path: './output/mobile'
        int8_model_save_path: './output/int8'
        weight_bits: 8
        activation_bits: 8
        weight_quantize_type: 'abs_max'
        activation_quantize_type: 'abs_max'
compressor:
    epoch: 3
    #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
    checkpoint_path: './checkpoints/'
    strategies:
        - uniform_pruning_strategy
        - quantization_strategy
```

你可以按以上配置试一下，或这你把你修改epoch后的配置贴一下？
