### ISSUE TITLE
量化结束后未保存任何模型

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#3121]
使用的代码如下，但是并没有任何模型保存下来
```
    com_pass = Compressor(
        place,
        fluid.global_scope(),
        train_prog,
        train_reader=train_py_reader,
        train_feed_list=None,
        train_fetch_list=train_fetch_list,
        eval_program=test_prog,
        eval_reader=test_py_reader,
        eval_feed_list=None,
        eval_fetch_list=val_fetch_list,
        train_optimizer=None)

    com_pass.config(args.compress_config)
    com_pass.run()
```
config：
```
version: 1.0
strategies:
    quantization_strategy:
        class: 'QuantizationStrategy'
        start_epoch: 0
        end_epoch: 9
        float_model_save_path: './output/float'
        mobile_model_save_path: './output/mobile'
        int8_model_save_path: './output/int8'
        weight_bits: 8
        activation_bits: 8
        weight_quantize_type: 'abs_max'
        activation_quantize_type: 'range_abs_max'
        save_in_nodes: ['read_file_0.tmp_0']
        save_out_nodes: ['detection_output_0.tmp_0']
compressor:
    epoch: 10
    checkpoint_path: './checkpoints_quan_fintune/'
    strategies:
        - quantization_strategy
```
