### ISSUE TITLE
PaddleDetection 中 DataFeed 中的 `target_size` 是否可改成配置或参数形式？

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/models#3128]
如下图所示，ppdet 中的 DataFeed 的中，对 `target_size` 参数使用了硬编码的形式，导致修改输入到网络的 tensor 的 shape 不是很方便，改成在 config 里配置或者参数的形式是否更合理？

![image](https://user-images.githubusercontent.com/37564754/63222931-c0068a80-c1e0-11e9-9a8b-3ded7d6e0158.png)

另外，此处[model zoo doc](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/MODEL_ZOO.md)存在一个拼写错误，可以顺便改了
![image](https://user-images.githubusercontent.com/37564754/63222991-6488cc80-c1e1-11e9-84ad-d369e4426f5e.png)

**Comment by zhaoyuchen2018** [comment]
请检测库同学看看能否改进一下

**Comment by qingqing01** [comment]
@mzchtx  实际是可以config里配置的，为了简化config，避免后续改动，导致config需要大量的改动，我们去掉了config里对数据预处理的配置。

1. 在config里加，可以参考:

https://github.com/PaddlePaddle/models/pull/3095/files#diff-b32b0421358b237c922fa43549224cfa

```yaml
SSDTestFeed:
  batch_size: 1
  batch_transforms: []
  dataset:
    annotation: pascalvoc/VOCdevkit/VOC_all/ImageSets/Main/test.txt
    image_dir: pascalvoc/VOCdevkit/VOC_all/JPEGImages
  drop_last: false
  fields:
  - image
  image_shape: [3, 300, 300]
  num_workers: 8
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !ResizeImage
    interp: 1
    target_size: 300
    use_cv2: false
  - !Permute
     to_bgr: true
     channel_first: true
  shuffle: false
```

2. 也可以命令行里更改，如下示例，下面命令可运行

```
export PYTHONPATH=`pwd`:$PYTHONPATH
export CUDA_VISIBLE_DEVICES=0
TRANSFORM="[!DecodeImage {to_rgb: true},!ResizeImage {target_size: 512, use_cv2: false, interp: 1},!Permute {},!NormalizeImage {mean: [127.5,127.5,127.5],std:[127.502231,127.502231,127.502231],is_scale: false, is_channel_first: true}]"
python tools/infer.py -c configs/ssd/ssd_mobilenet_v1_voc.yml  --infer_img demo/000000014439.jpg  \
    -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar SSDTestFeed.image_shape=[3,512,512] SSDTestFeed.sample_transforms="${TRANSFORM}"
```
