### ISSUE TITLE
deeplabv3_xception65给出的miou=0.79，直接下载权重使用paddleseg评测只有0.59，是否可以给出复现的具体过程

### ISSUE THREAD

**Issue by stuhailiu** [PaddlePaddle/models#3359]
从github上下载deeplabv3_xception65_bn的权重参数，直接用paddleseg加载进行预测，使用默认的参数配置，输出的miou只有0.59

[EVAL]#image=500 acc=0.9114 IoU=0.5917
[EVAL]Category IoU: [0.9464 0.6721 0.8490 0.4693 0.4214 0.2727 0.3392 0.4761 0.8506 0.5234 0.8905 0.5392 0.2792 0.8313 0.6819 0.7244 0.6624 0.2800 0.5329]
[EVAL]Category Acc: [0.9841 0.8093 0.9030 0.7519 0.6044 0.5073 0.6370 0.7179 0.8937 0.7346 0.9478 0.7009 0.5528 0.8958 0.7783 0.8263 0.8320 0.6636 0.6784]

参数配置如下
TRAIN_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
EVAL_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (512, 512) # (width, height), for unpadding

    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling

    MAX_SCALE_FACTOR: 1.25  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 4
DATASET:
    DATA_DIR: "E:/dakeai/cityscape"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "E:/dakeai/cityscape/list/cityscapes_val_list.txt"
    TRAIN_FILE_LIST: "E:/dakeai/cityscape/list/cityscapes_train_list.txt"
    VAL_FILE_LIST: "E:/dakeai/cityscape/list/cityscapes_val_list.txt"
    VIS_FILE_LIST: "E:/dakeai/cityscape/list/cityscapes_val_list.txt"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
MODEL:
    MODEL_NAME: "deeplabv3p"
    DEFAULT_NORM_TYPE: "bn"
    DEEPLAB:
        BACKBONE: "xception_65"
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_xception65_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/deeplabv3p_xception65_bn_pet/"
    SNAPSHOT_EPOCH: 10
TEST:
    TEST_MODEL: "./saved_model/deeplabv3p_xception65_bn_pet/final"
SOLVER:
    NUM_EPOCHS: 100
    LR: 0.005
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"

**Comment by LutaoChu** [comment]
你的配置适用于unet。
建议使用这个配置：
```
EVAL_CROP_SIZE: (2049, 1025) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (640, 640) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 4
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
TEST:
    TEST_MODEL: "pretrained_model/deeplabv3p_xception65_bn_cityscapes/"
TRAIN:
    MODEL_SAVE_DIR: ""
    PRETRAINED_MODEL_DIR: u""
    SNAPSHOT_EPOCH: 10
    SYNC_BATCH_NORM: True
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 700
```
